### PR TITLE
Add `RMI-PACTA/developers` as `.md` `CODEOWNERS`

### PR DESCRIPTION
**Pull request by jdhoffa**
... except for `README.md`

This will:
* Automatically enforce consensus review on all `practices`
* Still allow me to make structural changes to the main page/ hugo website, other non-practice parts of this repository

### CODE REVIEW

**Review by cjyetman — CHANGES_REQUESTED** [review]
GitHub webGUI says this contains an error, i.e. `Invalid owner on line 8:`

**Comment by jdhoffa** [comment]
Damn!

**Comment by jdhoffa** [comment]
Ok should be fixed, appears like that is the preferred syntax recommended here:
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners

**Review by cjyetman — APPROVED** [review]

**Comment by jdhoffa** [comment]
Ah interesting, noted. 

But note, I have already set the `CODEOWNER` requirement here (I do this by default on all my repos)
Screenshot 2024-02-15 at 15 21 59

**Pull request merged**
